name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PHP_VERSION: '8.5'
      PHPUNIT_VERSION: '13.0.5'

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Setup PHP ${{ env.PHP_VERSION }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Download PHPUnit ${{ env.PHPUNIT_VERSION }}
        run: wget https://phar.phpunit.de/phpunit-${{ env.PHPUNIT_VERSION }}.phar

      - name: Run Tests
        run: php phpunit-${{ env.PHPUNIT_VERSION }}.phar tests --configuration tests/phpunit.xml